run_id: resnet50_e50_isz224_lr0.001_b32_ft
experiment: exp1_model_compare
pipeline: pipeline2
mode: production
reused: false
hyperparams:
  epochs: 50
  input_size: 224
  lr: 0.001
  batch: 32
  strategy: finetune
  patience: 10
  seed: 42
  weight_decay: 0.0001
  workers: 4
  model: resnet50
device: null
started_at: '2026-06-16T15:44:38+00:00'
finished_at: '2026-06-16T16:20:35+00:00'
status: completed
